import Papa from 'papaparse';

const extronData = [
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1606',
        'Device_Type': 'Scaler_Switcher',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '6',
        'Video_Outputs': '1',
        'Video_Input_Types': 'HDMI(2),VGA(4)',
        'Video_Output_Types': 'HDMI',
        'Audio_Inputs': '6',
        'Audio_Outputs': '1',
        'Audio_Types': 'Analog,HDMI_Embedded',
        'Max_Resolution': '1920x1200',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': 'Auto-switching,Logo_Insert'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1608',
        'Device_Type': 'Scaler_Switcher_DSP',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '8',
        'Video_Outputs': '1',
        'Video_Input_Types': 'HDMI(4),VGA(4)',
        'Video_Output_Types': 'HDMI',
        'Audio_Inputs': '8',
        'Audio_Outputs': '2',
        'Audio_Types': 'Analog,HDMI_Embedded,DSP',
        'Max_Resolution': '1920x1200',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': 'DSP,Auto-switching,Logo_Insert'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1804',
        'Device_Type': 'Scaler_Switcher',
        'Firmware_Version': '1.xx',
        'Video_Inputs': '4',
        'Video_Outputs': '1',
        'Video_Input_Types': 'HDMI(4)',
        'Video_Output_Types': 'HDMI',
        'Audio_Inputs': '4',
        'Audio_Outputs': '1',
        'Audio_Types': 'HDMI_Embedded',
        'Max_Resolution': '4K/60',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': '4K_Scaling,HDR,Auto-switching'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1808',
        'Device_Type': 'Scaler_Switcher',
        'Firmware_Version': '1.xx',
        'Video_Inputs': '8',
        'Video_Outputs': '1',
        'Video_Input_Types': 'HDMI(8)',
        'Video_Output_Types': 'HDMI',
        'Audio_Inputs': '8',
        'Audio_Outputs': '1',
        'Audio_Types': 'HDMI_Embedded',
        'Max_Resolution': '4K/60',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': '4K_Scaling,HDR,Auto-switching'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'DTP2 CrossPoint 82',
        'Device_Type': 'Matrix_Scaler_Switcher',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '8',
        'Video_Outputs': '2',
        'Video_Input_Types': 'HDMI(8)',
        'Video_Output_Types': 'HDMI(2)',
        'Audio_Inputs': '8',
        'Audio_Outputs': '2',
        'Audio_Types': 'HDMI_Embedded,Dante',
        'Max_Resolution': '4K/60',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': '4K_Scaling,Vector_4K,Independent_Audio_Routing'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'DTP2 CrossPoint 84',
        'Device_Type': 'Matrix_Scaler_Switcher',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '8',
        'Video_Outputs': '4',
        'Video_Input_Types': 'HDMI(8)',
        'Video_Output_Types': 'HDMI(4)',
        'Audio_Inputs': '8',
        'Audio_Outputs': '4',
        'Audio_Types': 'HDMI_Embedded,Dante',
        'Max_Resolution': '4K/60',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': '4K_Scaling,Vector_4K,Independent_Audio_Routing'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1604 DTP',
        'Device_Type': 'Scaler_Switcher_DTP',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '4',
        'Video_Outputs': '2',
        'Video_Input_Types': 'HDMI(2),VGA(2)',
        'Video_Output_Types': 'HDMI,DTP',
        'Audio_Inputs': '4',
        'Audio_Outputs': '2',
        'Audio_Types': 'Analog,HDMI_Embedded',
        'Max_Resolution': '4K/30',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': 'DTP_Output,Auto-switching'
    },
    {
        'Manufacturer': 'Extron',
        'Model': 'IN1608 xi',
        'Device_Type': 'Scaler_Switcher_DSP',
        'Firmware_Version': '2.xx',
        'Video_Inputs': '8',
        'Video_Outputs': '1',
        'Video_Input_Types': 'HDMI(4),VGA(4)',
        'Video_Output_Types': 'HDMI',
        'Audio_Inputs': '8',
        'Audio_Outputs': '4',
        'Audio_Types': 'Analog,HDMI_Embedded,DSP,AEC',
        'Max_Resolution': '4K/30',
        'EDID_Management': 'Yes',
        'IP_Control': 'Yes',
        'IP_Port': '23',
        'RS232_Control': 'Yes',
        'Baud_Rate': '9600',
        'Command_Format': 'ASCII',
        'Command_Termination': 'CR/LF',
        'Query_Support': 'Yes',
        'Status_Feedback': 'Yes',
        'Special_Features': 'DSP,AEC,Auto-switching,Logo_Insert'
    }
];

// Convert to CSV with headers
const csv = Papa.unparse(extronData);
console.log(csv);